### ISSUE TITLE
off by one error in the cons file

### ISSUE THREAD

**Issue by lheisler** [oicr-gsi/debarcer#121]
a review of the consensus file reported uncollapsed depths when compared to those observed by running mpileup directly on the bam shows these to be shifted by a base.

debugging suggests the issue is in the functions
get_collapsed_seq
get_uncollapsed_seq

each has the line
pos = pileupcolumn.reference_pos -1

removing the -1 from this line appears to correct the issue
It's possible the -1 was added to address a previous issue, so some additional testing would be good

**Comment by lheisler** [comment]
this doesn't fully correct the issue,

extraction of non reference bases still has the off by one error, each of the two functions has this line
alt_base = read_data.query_sequence[read.query_position]-1
which needs to be change to
alt_base = read_data.query_sequence[read.query_position]

**Comment by lheisler** [comment]
seems that these two functions can be merged
get_collapsed_seq
get_uncollapsed_seq

as they do mostly the same thing

the current get_collapses_seq function requires a minimum family size input.  providing this the 0 indicator ie. no collapse, would run across all reads, and not collapse groups or pay attention to family size.

**Comment by rjovelin** [comment]
The issue was due to dealing with 0-based and 1-based coordinates inconsistently.
All functions are now using 0-based coordinates. Coordinates in input/output files is 1-based, and are converted to/back 0-based by the main script debarcer.py.

This issue is now fixed as shown from comparison or position, reference in consensus files and samtools pileup
