### ISSUE TITLE
requesting collapse with family size 0 introduces errors in the output

### ISSUE THREAD

**Issue by lheisler** [oicr-gsi/debarcer#122]
input to collapse is a list of minimum family sizes to calculate coverage and consensus
eg, -f 1,2,3,5,10

family size 0 is used also, and this is coding for uncollapsed sequence of any family size

if for some reason, the input to debarcer is
-f 0,1,2,3,5,10
an error is introduced
The cons lines with family size 0 somehow get the consensus depth of f=1, as opposed to being equal to the uncollapsed depth

this is likely because uncollapsed is assesses separately from collapsed at various family sizes.  when 0 is in the list of family sizes, the function tries to calculate collapsed values with family size =0, which doesn't really make sense

two solutions (maybe implement both)
1. Don't allow the user to include 0 in the list of family sizes
2. if it is allowed, ensure that this size is not passed to the get_consensus_seq function

**Comment by rjovelin** [comment]
Fixed issue. 0 is allowed in the list of family sizes - 0,1,2,3
if 0 in list --> call generate_uncollapsed to get consensus data
if 0 not in list --> call generate_uncollapsed to get consensus data
Thus it is not necessary to pass 0 in the list of family size but it calls the proper function if it is passed instead of issuing errors
